---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Big Chickens!

background:
  image: /images/sky.jpg
  blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 75 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 25 # 0-100

showStats: true
theme: dark
color: slate

layout:
  Services:
    style: row
    columns: 4
  Docker:
    style: row
    columns: 1

headerStyle: clean
hideVersion: true
statusStyle: "dot"

